version: 2

before:
  hooks:
    - go mod tidy
    - go test -v ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  use: 'github'
  filters:
    exclude:
      - "^docs:"
      - "^test:"
